### ISSUE TITLE
burgers equation  PINN idea

### ISSUE THREAD

**Issue by Aiswaryamg** [maziarraissi/PINNs#43]
In burgers equation are we taking the data from boundary to train the nueral network. From what I understood in the paper we use information from the boundary to train data. But in code we are selcting random values from the whole domain. Am I correct or did I read the code wrong? burgers equation PINN idea

**Comment by nish-ant** [comment]
I think you are referring the code for the identification problem (discussed in Part II of the paper) whereas you need to refer the code for the inference problem (Part I).

The points are selected at random from the whole domain in the identification problem:
https://github.com/maziarraissi/PINNs/blob/0542794b0a91b9e8764a38f5fc9cd9647a3929ba/appendix/continuous_time_identification%20(Burgers)/Burgers.py#L178-L180

whereas only the solution at the boundaries is used in the inference problem (indices `0:1` and `-1` correspond to the boundary data):
https://github.com/maziarraissi/PINNs/blob/0542794b0a91b9e8764a38f5fc9cd9647a3929ba/appendix/continuous_time_inference%20(Burgers)/Burgers.py#L164-L167
